### PR TITLE
feat: BREAKING Use new message and curve formats

### PR DESCRIPTION
**Pull request by sentientwaffle**
* Remove schemas/LiquidityCurve (curves are now stored as a base64-encoded string)
* `schemas/Message`: Add `id`, `ilp`, `custom`; remove `data`.

### CODE REVIEW

**Comment by michielbdejong** [comment]
not sure if this is technically breaking, since all old formats are still also supported by the schema. but not worth discussing very long over, if you feel it's breaking, then tag a major. :)

**Comment by sentientwaffle** [comment]
The "BREAKING" refers to the change to the `Routes` format.

**Comment by michielbdejong** [comment]
ah, of course.

OK, then it's also breaking for ilp-kit, sorry for the confusion!

**Comment by michielbdejong** [comment]
Sorry, didn't mean to close the issue, I must have hit 'Close and comment' by accident!

**Pull request merged**
